# Generated by Django 4.0.4 on 2024-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('medicines', models.TextField()),
                ('diet_recommendations', models.TextField()),
                ('recommended_tests', models.TextField()),
                ('additional_description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
