# Generated by Django 4.0.4 on 2024-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiCare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionform',
            old_name='additional_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='prescriptionform',
            old_name='diet_recommendations',
            new_name='diet',
        ),
        migrations.RenameField(
            model_name='prescriptionform',
            old_name='patient_name',
            new_name='patientName',
        ),
        migrations.RenameField(
            model_name='prescriptionform',
            old_name='recommended_tests',
            new_name='tests',
        ),
        migrations.AddField(
            model_name='prescriptionform',
            name='patientUserName',
            field=models.CharField(default='default_username', max_length=100),
            preserve_default=False,
        ),
    ]
