# Generated by Django 4.0.4 on 2024-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiCare', '0002_rename_additional_description_prescriptionform_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionform',
            name='doctorUserName',
            field=models.CharField(default='testuser', max_length=100),
            preserve_default=False,
        ),
    ]
