# Generated by Django 4.0.4 on 2024-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiCare', '0005_patient_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visual_verification',
            field=models.CharField(default='2-yellow 3-cyan', max_length=255),
            preserve_default=False,
        ),
    ]
